export interface Product {
  id: string;
  name: string;
  price: number;
  description: string;
  image: string;
  category: string;
  stock: number;
}

export const products: Product[] = [
  // Baby Size Animals (0.75" - $1.00)
  {
    id: 'baby-dragon',
    name: 'Baby Dragon - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated dragon fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Perfect for stress relief and fun!',
    image: 'https://images.unsplash.com/photo-1578632292335-df3abbb0d586?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-shark',
    name: 'Baby Shark - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated shark fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Great for sensory play!',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-unicorn',
    name: 'Baby Unicorn - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated unicorn fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Magical and fun!',
    image: 'https://images.unsplash.com/photo-1591696205602-2f950c417cb9?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-dolphin',
    name: 'Baby Dolphin - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated dolphin fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Perfect gift!',
    image: 'https://images.unsplash.com/photo-1607153333879-c174d265f1d2?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-panda',
    name: 'Baby Panda - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated panda fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Adorable and fun!',
    image: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-narwhal',
    name: 'Baby Narwhal - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated narwhal fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Unique ocean creature!',
    image: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },

  // Big Size Animals (1.5" - $5.00)
  {
    id: 'big-dragon',
    name: 'Big Dragon - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated dragon fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Detailed and perfect for display!',
    image: 'https://images.unsplash.com/photo-1578632292335-df3abbb0d586?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-shark',
    name: 'Big Shark - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated shark fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Great for collectors!',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-unicorn',
    name: 'Big Unicorn - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated unicorn fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Magical and enchanting!',
    image: 'https://images.unsplash.com/photo-1591696205602-2f950c417cb9?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-sea-turtle',
    name: 'Big Sea Turtle - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated sea turtle fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Ocean lover favorite!',
    image: 'https://images.unsplash.com/photo-1591025207163-942350e47db2?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-alligator',
    name: 'Big Alligator - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated alligator fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Realistic reptile fun!',
    image: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-fox',
    name: 'Big Fox - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated fox fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Cute woodland creature!',
    image: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },

  // Additional Baby Animals
  {
    id: 'baby-alligator',
    name: 'Baby Alligator - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated alligator fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Fierce and fun!',
    image: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-axolotl',
    name: 'Baby Axolotl - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated axolotl fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Unique amphibian!',
    image: 'https://images.unsplash.com/photo-1617510029409-48e6eb19e1c3?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-beaver',
    name: 'Baby Beaver - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated beaver fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Hardworking cutie!',
    image: 'https://images.unsplash.com/photo-1633621827350-4e30e9bbb9fa?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-cat',
    name: 'Baby Cat - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated cat fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Purr-fect companion!',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-crocodile',
    name: 'Baby Crocodile - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated crocodile fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Snappy fun!',
    image: 'https://images.unsplash.com/photo-1550699026-4114bbf4fb49?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-arctic-fox',
    name: 'Baby Arctic Fox - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated arctic fox fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Snowy cuteness!',
    image: 'https://images.unsplash.com/photo-1552825973-5a6f1e7a3d6e?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-fox',
    name: 'Baby Fox - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated fox fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Woodland wonder!',
    image: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-goldfish',
    name: 'Baby Goldfish - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated goldfish fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Golden swimmer!',
    image: 'https://images.unsplash.com/photo-1520990269687-b48f8df42d7f?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-mouse',
    name: 'Baby Mouse - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated mouse fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Tiny and adorable!',
    image: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-otter',
    name: 'Baby Otter - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated otter fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Playful river friend!',
    image: 'https://images.unsplash.com/photo-1545671913-b89ac1b4ac10?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-pig',
    name: 'Baby Pig - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated pig fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Oink-tastic!',
    image: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-platypus',
    name: 'Baby Platypus - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated platypus fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Unique creature!',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-polar-bear',
    name: 'Baby Polar Bear - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated polar bear fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Arctic cuddler!',
    image: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-rhino',
    name: 'Baby Rhino - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated rhino fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Mighty mini!',
    image: 'https://images.unsplash.com/photo-1551927336-575d8e829c8a?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-sea-turtle',
    name: 'Baby Sea Turtle - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated sea turtle fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Ocean baby!',
    image: 'https://images.unsplash.com/photo-1591025207163-942350e47db2?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },

  // Additional Big Animals
  {
    id: 'big-axolotl',
    name: 'Big Axolotl - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated axolotl fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Detailed amphibian!',
    image: 'https://images.unsplash.com/photo-1617510029409-48e6eb19e1c3?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-beaver',
    name: 'Big Beaver - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated beaver fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Builder buddy!',
    image: 'https://images.unsplash.com/photo-1633621827350-4e30e9bbb9fa?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-cat',
    name: 'Big Cat - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated cat fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Feline favorite!',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-crocodile',
    name: 'Big Crocodile - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated crocodile fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Detailed predator!',
    image: 'https://images.unsplash.com/photo-1550699026-4114bbf4fb49?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-arctic-fox',
    name: 'Big Arctic Fox - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated arctic fox fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Winter beauty!',
    image: 'https://images.unsplash.com/photo-1552825973-5a6f1e7a3d6e?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-dolphin',
    name: 'Big Dolphin - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated dolphin fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Ocean intelligence!',
    image: 'https://images.unsplash.com/photo-1607153333879-c174d265f1d2?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-goldfish',
    name: 'Big Goldfish - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated goldfish fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Lucky swimmer!',
    image: 'https://images.unsplash.com/photo-1520990269687-b48f8df42d7f?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-mouse',
    name: 'Big Mouse - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated mouse fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Charming critter!',
    image: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-narwhal',
    name: 'Big Narwhal - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated narwhal fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Unicorn of the sea!',
    image: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-otter',
    name: 'Big Otter - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated otter fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Playful swimmer!',
    image: 'https://images.unsplash.com/photo-1545671913-b89ac1b4ac10?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-panda',
    name: 'Big Panda - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated panda fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Bamboo lover!',
    image: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-pig',
    name: 'Big Pig - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated pig fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Farm favorite!',
    image: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-platypus',
    name: 'Big Platypus - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated platypus fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Quirky wonder!',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-polar-bear',
    name: 'Big Polar Bear - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated polar bear fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Arctic king!',
    image: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-rhino',
    name: 'Big Rhino - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated rhino fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Powerful beast!',
    image: 'https://images.unsplash.com/photo-1551927336-575d8e829c8a?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },

  // Flexi Zoo Models - Regular Size ($20)
  {
    id: 'flexi-squirrel',
    name: 'Squirrel - Flexi Zoo Model',
    price: 20.00,
    description: 'Highly detailed flexi zoo squirrel. Premium quality 3D printed model with realistic articulation.',
    image: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-squirrel-santa',
    name: 'Squirrel + Santa Hat - Flexi Zoo Model',
    price: 20.00,
    description: 'Festive flexi zoo squirrel with Santa hat. Perfect holiday decoration!',
    image: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-highland-cow',
    name: 'Highland Cow - Flexi Zoo Model',
    price: 20.00,
    description: 'Highly detailed flexi zoo Highland cow. Beautiful articulated model with realistic features.',
    image: 'https://images.unsplash.com/photo-1561083771-5a23e4f6c190?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-dairy-cow',
    name: 'Dairy Cow - Flexi Zoo Model',
    price: 20.00,
    description: 'Highly detailed flexi zoo dairy cow. Premium articulated farm animal model.',
    image: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-roborattler',
    name: 'RoboRattler - Robot Rattlesnake',
    price: 20.00,
    description: 'Futuristic robot rattlesnake flexi model. Unique mechanical design meets nature.',
    image: 'https://images.unsplash.com/photo-1545429283-b94e1e93f0b6?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-wolf',
    name: 'Wolf - Flexi Zoo Model',
    price: 20.00,
    description: 'Highly detailed flexi zoo wolf. Majestic predator with realistic articulation.',
    image: 'https://images.unsplash.com/photo-1614027164847-1b28cfe1df60?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-red-panda',
    name: 'Red Panda - Flexi Zoo Model',
    price: 20.00,
    description: 'Adorable flexi zoo red panda. Premium quality with intricate details.',
    image: 'https://images.unsplash.com/photo-1497206365907-f5e630693df0?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-sloth',
    name: 'Sloth - Flexi Zoo Model',
    price: 20.00,
    description: 'Highly detailed flexi zoo sloth. Relaxed and realistic articulation.',
    image: 'https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-flapjack-octopus',
    name: 'Flapjack Octopus - Flexi Zoo Model',
    price: 20.00,
    description: 'Adorable flexi zoo flapjack octopus. Unique deep-sea creature design.',
    image: 'https://images.unsplash.com/photo-1545671913-b89ac1b4ac10?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-skunk',
    name: 'Skunk - Flexi Zoo Model',
    price: 20.00,
    description: 'Highly detailed flexi zoo skunk. Premium quality with realistic features.',
    image: 'https://images.unsplash.com/photo-1572827921212-8d1a7b0b7b1e?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-warthog',
    name: 'Warthog - Flexi Zoo Model',
    price: 20.00,
    description: 'Highly detailed flexi zoo warthog. Rugged and realistic African wildlife.',
    image: 'https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-polar-bear',
    name: 'Polar Bear - Flexi Zoo Model',
    price: 20.00,
    description: 'Majestic flexi zoo polar bear. Arctic predator with premium articulation.',
    image: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-polar-bear-santa',
    name: 'Polar Bear + Santa Hat - Flexi Zoo Model',
    price: 20.00,
    description: 'Festive flexi zoo polar bear with Santa hat. Perfect winter decoration!',
    image: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-manatee',
    name: 'Manatee - Flexi Zoo Model',
    price: 20.00,
    description: 'Gentle flexi zoo manatee. Sea cow with smooth articulation.',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-river-otter',
    name: 'River Otter - Flexi Zoo Model',
    price: 20.00,
    description: 'Playful flexi zoo river otter. Highly detailed aquatic mammal.',
    image: 'https://images.unsplash.com/photo-1604074131665-7a4b12c2e9b0?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-tarantula',
    name: 'Tarantula - Flexi Zoo Model',
    price: 20.00,
    description: 'Highly detailed flexi zoo tarantula. Realistic spider with articulated legs.',
    image: 'https://images.unsplash.com/photo-1585013568957-a8a1f311a009?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-raccoon',
    name: 'Raccoon - Flexi Zoo Model',
    price: 20.00,
    description: 'Mischievous flexi zoo raccoon. Premium quality with realistic details.',
    image: 'https://images.unsplash.com/photo-1497993950456-cdb73e8350ce?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-robotortoise',
    name: 'RoboTortoise - Flexi Zoo Model',
    price: 20.00,
    description: 'Futuristic robot tortoise flexi model. Mechanical meets natural design.',
    image: 'https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-quokka',
    name: 'Quokka - Flexi Zoo Model',
    price: 20.00,
    description: 'Smiling flexi zoo quokka. World\'s happiest animal in premium detail.',
    image: 'https://images.unsplash.com/photo-1615963244664-5b845b2025ee?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-rat',
    name: 'Rat - Flexi Zoo Model',
    price: 20.00,
    description: 'Highly detailed flexi zoo rat. Intelligent rodent with realistic features.',
    image: 'https://images.unsplash.com/photo-1598024055266-e772a5f8c128?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-triceratops',
    name: 'Triceratops - Flexi Zoo Model',
    price: 20.00,
    description: 'Mighty flexi zoo triceratops. Prehistoric dinosaur with premium articulation.',
    image: 'https://images.unsplash.com/photo-1578632292335-df3abbb0d586?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-platypus',
    name: 'Platypus - Flexi Zoo Model',
    price: 20.00,
    description: 'Unique flexi zoo platypus. Australia\'s oddest mammal in detailed form.',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-tortoise',
    name: 'Tortoise - Flexi Zoo Model',
    price: 20.00,
    description: 'Highly detailed flexi zoo tortoise. Ancient reptile with realistic shell.',
    image: 'https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-opossum',
    name: 'Opossum - Flexi Zoo Model',
    price: 20.00,
    description: 'Adorable flexi zoo opossum. Marsupial with premium articulation.',
    image: 'https://images.unsplash.com/photo-1573920111312-04f1c8b8b1b9?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-ghost-crab',
    name: 'Ghost Crab - Flexi Zoo Model',
    price: 20.00,
    description: 'Highly detailed flexi zoo ghost crab. Beach dweller with articulated legs.',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-capybara',
    name: 'Capybara - Flexi Zoo Model',
    price: 20.00,
    description: 'Chill flexi zoo capybara. World\'s largest rodent in premium quality.',
    image: 'https://images.unsplash.com/photo-1563291074-2bf8677ac0e5?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-ferret',
    name: 'Ferret - Flexi Zoo Model',
    price: 20.00,
    description: 'Playful flexi zoo ferret. Energetic mustelid with realistic features.',
    image: 'https://images.unsplash.com/photo-1548302272-ffb7780c3d31?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-tree-frog',
    name: 'Tree Frog - Flexi Zoo Model',
    price: 20.00,
    description: 'Vibrant flexi zoo tree frog. Tropical amphibian with detailed articulation.',
    image: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-robolotl',
    name: 'Robolotl - Robot Axolotl',
    price: 20.00,
    description: 'Futuristic robot axolotl flexi model. Mechanical salamander design.',
    image: 'https://images.unsplash.com/photo-1617639776827-f0025619e8d2?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-tiger',
    name: 'Tiger - Flexi Zoo Model',
    price: 20.00,
    description: 'Majestic flexi zoo tiger. Powerful predator with premium articulation.',
    image: 'https://images.unsplash.com/photo-1551316679-9c6ae9dec224?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-tardigrade',
    name: 'Tardigrade - Flexi Zoo Model',
    price: 20.00,
    description: 'Microscopic marvel flexi zoo tardigrade. Water bear in detailed form.',
    image: 'https://images.unsplash.com/photo-1545429283-b94e1e93f0b6?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-crested-gecko',
    name: 'Crested Gecko - Flexi Zoo Model',
    price: 20.00,
    description: 'Highly detailed flexi zoo crested gecko. Exotic reptile with realistic features.',
    image: 'https://images.unsplash.com/photo-1550699026-4114bbf4fb49?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-bunny',
    name: 'Bunny Rabbit - Flexi Zoo Model',
    price: 20.00,
    description: 'Adorable flexi zoo bunny. Premium quality rabbit with soft features.',
    image: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-great-white-shark',
    name: 'Great White Shark - Flexi Zoo Model',
    price: 20.00,
    description: 'Powerful flexi zoo great white shark. Ocean apex predator in premium detail.',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-rattlesnake',
    name: 'Rattlesnake - Flexi Zoo Model',
    price: 20.00,
    description: 'Highly detailed flexi zoo rattlesnake. Venomous serpent with realistic scales.',
    image: 'https://images.unsplash.com/photo-1545429283-b94e1e93f0b6?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-hammerhead-shark',
    name: 'Hammerhead Shark - Flexi Zoo Model',
    price: 20.00,
    description: 'Unique flexi zoo hammerhead shark. Distinctive predator with premium articulation.',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-ball-python',
    name: 'Ball Python Snake - Flexi Zoo Model',
    price: 20.00,
    description: 'Beautiful flexi zoo ball python. Docile snake with intricate pattern details.',
    image: 'https://images.unsplash.com/photo-1545429283-b94e1e93f0b6?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-bat',
    name: 'Bat - Flexi Zoo Model',
    price: 20.00,
    description: 'Highly detailed flexi zoo bat. Night flyer with articulated wings.',
    image: 'https://images.unsplash.com/photo-1551993005-75c4131b6bd8?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-leopard-gecko',
    name: 'Leopard Gecko - Flexi Zoo Model',
    price: 20.00,
    description: 'Spotted flexi zoo leopard gecko. Desert lizard with realistic details.',
    image: 'https://images.unsplash.com/photo-1550699026-4114bbf4fb49?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-bearded-dragon',
    name: 'Bearded Dragon - Flexi Zoo Model',
    price: 20.00,
    description: 'Majestic flexi zoo bearded dragon. Premium quality Australian lizard.',
    image: 'https://images.unsplash.com/photo-1550699026-4114bbf4fb49?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-axolotl',
    name: 'Axolotl - Flexi Zoo Model',
    price: 20.00,
    description: 'Adorable flexi zoo axolotl. Mexican salamander with premium articulation.',
    image: 'https://images.unsplash.com/photo-1617639776827-f0025619e8d2?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-big-smile-axolotl',
    name: 'Big Smile Axolotl - Flexi Zoo Model',
    price: 20.00,
    description: 'Happy flexi zoo axolotl with big smile. Cheerful salamander design.',
    image: 'https://images.unsplash.com/photo-1617639776827-f0025619e8d2?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-zombeardie',
    name: 'Zombeardie: Bearded Dragon - Flexi Zoo Model',
    price: 20.00,
    description: 'Spooky zombie bearded dragon flexi model. Halloween special edition!',
    image: 'https://images.unsplash.com/photo-1550699026-4114bbf4fb49?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-jack-o-lantern',
    name: 'Jack-O-Lantern Set - Flexi Zoo Model',
    price: 20.00,
    description: 'Festive jack-o-lantern flexi set. Perfect Halloween decoration!',
    image: 'https://images.unsplash.com/photo-1509557965875-b88c97052f0e?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-eye-licking-gecko',
    name: 'Eye Licking Leopard Gecko - Flexi Zoo Model',
    price: 20.00,
    description: 'Unique flexi zoo leopard gecko in eye-licking pose. Realistic behavior detail!',
    image: 'https://images.unsplash.com/photo-1550699026-4114bbf4fb49?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-santa-beardies',
    name: 'Santa Beardies - Flexi Zoo Model',
    price: 20.00,
    description: 'Festive bearded dragons with Santa theme. Holiday special edition!',
    image: 'https://images.unsplash.com/photo-1550699026-4114bbf4fb49?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-little-ball-pythons',
    name: 'Little Ball Pythons - Flexi Zoo Model',
    price: 20.00,
    description: 'Adorable little ball pythons flexi set. Multiple small snakes in premium detail.',
    image: 'https://images.unsplash.com/photo-1545429283-b94e1e93f0b6?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-fruit-bat',
    name: 'Fruit Bat - Flexi Zoo Model',
    price: 20.00,
    description: 'Highly detailed flexi zoo fruit bat. Flying fox with realistic wings.',
    image: 'https://images.unsplash.com/photo-1551993005-75c4131b6bd8?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-little-rattlesnakes',
    name: 'Little Rattlesnakes - Flexi Zoo Model',
    price: 20.00,
    description: 'Cute little rattlesnakes flexi set. Multiple baby rattlers in detail.',
    image: 'https://images.unsplash.com/photo-1545429283-b94e1e93f0b6?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-jackalopes',
    name: 'Jackalopes - Flexi Zoo Model',
    price: 20.00,
    description: 'Mythical flexi zoo jackalopes. Rabbit-antelope hybrid in premium quality.',
    image: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-gargoyle-gecko',
    name: 'Gargoyle Gecko - Flexi Zoo Model',
    price: 20.00,
    description: 'Unique flexi zoo gargoyle gecko. Exotic reptile with intricate features.',
    image: 'https://images.unsplash.com/photo-1550699026-4114bbf4fb49?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-axolotl-redux',
    name: 'Axolotl Redux - Flexi Zoo Model',
    price: 20.00,
    description: 'Enhanced flexi zoo axolotl redux. Improved design with premium details.',
    image: 'https://images.unsplash.com/photo-1617639776827-f0025619e8d2?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-roaring-tiger',
    name: 'Roaring Tiger & Saber-Tooth Tiger - Flexi Zoo Model',
    price: 20.00,
    description: 'Mighty flexi zoo tigers. Both modern and prehistoric predators!',
    image: 'https://images.unsplash.com/photo-1551316679-9c6ae9dec224?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-zombat',
    name: 'ZomBat - Flexi Zoo Model',
    price: 20.00,
    description: 'Spooky zombie bat flexi model. Halloween special with undead design!',
    image: 'https://images.unsplash.com/photo-1551993005-75c4131b6bd8?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-hognose-snake-set',
    name: 'Hognose Snake Set - Flexi Zoo Model',
    price: 20.00,
    description: 'Adorable hognose snake flexi set. Multiple poses of this dramatic snake.',
    image: 'https://images.unsplash.com/photo-1545429283-b94e1e93f0b6?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-winter-ferret',
    name: 'Winter Ferret - Flexi Zoo Model',
    price: 20.00,
    description: 'Festive winter ferret flexi model. Holiday themed mustelid design.',
    image: 'https://images.unsplash.com/photo-1548302272-ffb7780c3d31?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-whites-tree-frog',
    name: 'Whites Tree Frog - Flexi Zoo Model',
    price: 20.00,
    description: 'Dumpy tree frog flexi model. Charming Australian amphibian in detail.',
    image: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },
  {
    id: 'flexi-snail-slug',
    name: 'Snail & Slug w/Halloween Extras - Flexi Zoo Model',
    price: 20.00,
    description: 'Spooky snail and slug flexi set with Halloween decorations!',
    image: 'https://images.unsplash.com/photo-1545429283-b94e1e93f0b6?w=500&q=80',
    category: 'Flexi Zoo Models',
    stock: 15,
  },

  // Flexi Zoo Models - Mini Size ($10)
  {
    id: 'flexi-mini-bearded-dragon',
    name: 'MMMini Bearded Dragon - Flexi Zoo Model',
    price: 10.00,
    description: 'Compact mini flexi zoo bearded dragon. All the detail in a smaller size!',
    image: 'https://images.unsplash.com/photo-1550699026-4114bbf4fb49?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-axolotl',
    name: 'MMMini Axolotl - Flexi Zoo Model',
    price: 10.00,
    description: 'Adorable mini flexi zoo axolotl. Tiny salamander with big charm!',
    image: 'https://images.unsplash.com/photo-1617639776827-f0025619e8d2?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-bunny',
    name: 'MMMini Bunny - Flexi Zoo Model',
    price: 10.00,
    description: 'Tiny mini flexi zoo bunny. Premium rabbit in compact form!',
    image: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-ferret',
    name: 'MMMini Ferret - Flexi Zoo Model',
    price: 10.00,
    description: 'Playful mini flexi zoo ferret. Small but detailed mustelid!',
    image: 'https://images.unsplash.com/photo-1548302272-ffb7780c3d31?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-tiger',
    name: 'MMMini Tiger - Flexi Zoo Model',
    price: 10.00,
    description: 'Mighty mini flexi zoo tiger. Compact predator with premium articulation!',
    image: 'https://images.unsplash.com/photo-1551316679-9c6ae9dec224?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-opossum',
    name: 'MMMini Opossum - Flexi Zoo Model',
    price: 10.00,
    description: 'Cute mini flexi zoo opossum. Tiny marsupial with realistic details!',
    image: 'https://images.unsplash.com/photo-1573920111312-04f1c8b8b1b9?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-platypus',
    name: 'MMMini Platypus - Flexi Zoo Model',
    price: 10.00,
    description: 'Unique mini flexi zoo platypus. Australia\'s oddest mammal in mini form!',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-bats',
    name: 'MMMini Bats - Flexi Zoo Model',
    price: 10.00,
    description: 'Tiny mini flexi zoo bats. Small night flyers with articulated wings!',
    image: 'https://images.unsplash.com/photo-1551993005-75c4131b6bd8?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-cat',
    name: 'MMMini Cat - Flexi Zoo Model',
    price: 10.00,
    description: 'Adorable mini flexi zoo cat. Tiny feline with premium details!',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-tortoise',
    name: 'MMMini Tortoise - Flexi Zoo Model',
    price: 10.00,
    description: 'Tiny mini flexi zoo tortoise. Ancient reptile in compact size!',
    image: 'https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-raccoon',
    name: 'MMMini Raccoon - Flexi Zoo Model',
    price: 10.00,
    description: 'Mischievous mini flexi zoo raccoon. Small bandit with big personality!',
    image: 'https://images.unsplash.com/photo-1497993950456-cdb73e8350ce?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-raccoon-santa',
    name: 'MMMini Raccoon + Santa Hat - Flexi Zoo Model',
    price: 10.00,
    description: 'Festive mini raccoon with Santa hat. Holiday edition in mini form!',
    image: 'https://images.unsplash.com/photo-1497993950456-cdb73e8350ce?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-mouse',
    name: 'MMMini Mouse - Flexi Zoo Model',
    price: 10.00,
    description: 'Tiny mini flexi zoo mouse. Small rodent with intricate details!',
    image: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-capybara',
    name: 'MMMini Capybara - Flexi Zoo Model',
    price: 10.00,
    description: 'Chill mini flexi zoo capybara. World\'s largest rodent in mini size!',
    image: 'https://images.unsplash.com/photo-1563291074-2bf8677ac0e5?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-crested-gecko',
    name: 'MMMini Crested Gecko - Flexi Zoo Model',
    price: 10.00,
    description: 'Exotic mini flexi zoo crested gecko. Tiny lizard with premium details!',
    image: 'https://images.unsplash.com/photo-1550699026-4114bbf4fb49?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-lamb',
    name: 'MMMini Lamb - Flexi Zoo Model',
    price: 10.00,
    description: 'Adorable mini flexi zoo lamb. Tiny farm animal with soft features!',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-river-otter',
    name: 'MMMini River Otter - Flexi Zoo Model',
    price: 10.00,
    description: 'Playful mini flexi zoo river otter. Small aquatic mammal in detail!',
    image: 'https://images.unsplash.com/photo-1604074131665-7a4b12c2e9b0?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-dog',
    name: 'MMMini Dog - Flexi Zoo Model',
    price: 10.00,
    description: 'Loyal mini flexi zoo dog. Man\'s best friend in compact form!',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-great-white-shark',
    name: 'MMMini Great White Shark - Flexi Zoo Model',
    price: 10.00,
    description: 'Powerful mini flexi zoo great white. Ocean predator in mini size!',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-manatee',
    name: 'MMMini Manatee - Flexi Zoo Model',
    price: 10.00,
    description: 'Gentle mini flexi zoo manatee. Tiny sea cow with smooth articulation!',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-sloth',
    name: 'MMMini Sloth - Flexi Zoo Model',
    price: 10.00,
    description: 'Relaxed mini flexi zoo sloth. Tiny tree dweller in premium detail!',
    image: 'https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-sloth-santa',
    name: 'MMMini Sloth + Santa Hat - Flexi Zoo Model',
    price: 10.00,
    description: 'Festive mini sloth with Santa hat. Holiday edition for the slow season!',
    image: 'https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-hammerhead-shark',
    name: 'MMMini Hammerhead Shark - Flexi Zoo Model',
    price: 10.00,
    description: 'Unique mini flexi zoo hammerhead. Distinctive predator in mini form!',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },
  {
    id: 'flexi-mini-jackalopes',
    name: 'MMMini Jackalopes - Flexi Zoo Model',
    price: 10.00,
    description: 'Mythical mini flexi zoo jackalopes. Tiny rabbit-antelope hybrids!',
    image: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 20,
  },

  // Keychains
  {
    id: 'flexi-hognose-keychain',
    name: 'Hognose Snake Keychain - Flexi Zoo',
    price: 10.00,
    description: 'Adorable hognose snake keychain. Dramatic little snake for your keys!',
    image: 'https://images.unsplash.com/photo-1545429283-b94e1e93f0b6?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 30,
  },
  {
    id: 'flexi-rattlesnake-keychain',
    name: 'Rattlesnake Rattle Keychain - Flexi Zoo',
    price: 10.00,
    description: 'Rattlesnake rattle keychain. Perfect rattling accessory!',
    image: 'https://images.unsplash.com/photo-1545429283-b94e1e93f0b6?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 30,
  },
  {
    id: 'flexi-ball-python-keychain',
    name: 'Baby Ball Python Keychain - Flexi Zoo',
    price: 10.00,
    description: 'Cute baby ball python keychain. Tiny snake companion!',
    image: 'https://images.unsplash.com/photo-1545429283-b94e1e93f0b6?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 30,
  },
  {
    id: 'flexi-leopard-gecko-keychain',
    name: 'Leopard Gecko Tail Keychain - Flexi Zoo',
    price: 10.00,
    description: 'Leopard gecko tail keychain. Detachable tail design!',
    image: 'https://images.unsplash.com/photo-1550699026-4114bbf4fb49?w=500&q=80',
    category: 'Flexi Zoo Models - Mini',
    stock: 30,
  },
];
