export interface Product {
  id: string;
  name: string;
  price: number;
  description: string;
  image: string;
  category: string;
  stock: number;
}

export const products: Product[] = [
  // Baby Size Animals (0.75" - $1.00)
  {
    id: 'baby-dragon',
    name: 'Baby Dragon - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated dragon fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Perfect for stress relief and fun!',
    image: 'https://images.unsplash.com/photo-1578632292335-df3abbb0d586?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-shark',
    name: 'Baby Shark - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated shark fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Great for sensory play!',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-unicorn',
    name: 'Baby Unicorn - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated unicorn fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Magical and fun!',
    image: 'https://images.unsplash.com/photo-1591696205602-2f950c417cb9?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-dolphin',
    name: 'Baby Dolphin - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated dolphin fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Perfect gift!',
    image: 'https://images.unsplash.com/photo-1607153333879-c174d265f1d2?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-panda',
    name: 'Baby Panda - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated panda fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Adorable and fun!',
    image: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-narwhal',
    name: 'Baby Narwhal - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated narwhal fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Unique ocean creature!',
    image: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },

  // Big Size Animals (1.5" - $5.00)
  {
    id: 'big-dragon',
    name: 'Big Dragon - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated dragon fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Detailed and perfect for display!',
    image: 'https://images.unsplash.com/photo-1578632292335-df3abbb0d586?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-shark',
    name: 'Big Shark - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated shark fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Great for collectors!',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-unicorn',
    name: 'Big Unicorn - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated unicorn fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Magical and enchanting!',
    image: 'https://images.unsplash.com/photo-1591696205602-2f950c417cb9?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-sea-turtle',
    name: 'Big Sea Turtle - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated sea turtle fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Ocean lover favorite!',
    image: 'https://images.unsplash.com/photo-1591025207163-942350e47db2?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-alligator',
    name: 'Big Alligator - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated alligator fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Realistic reptile fun!',
    image: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-fox',
    name: 'Big Fox - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated fox fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Cute woodland creature!',
    image: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },

  // Additional Baby Animals
  {
    id: 'baby-alligator',
    name: 'Baby Alligator - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated alligator fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Fierce and fun!',
    image: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-axolotl',
    name: 'Baby Axolotl - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated axolotl fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Unique amphibian!',
    image: 'https://images.unsplash.com/photo-1617510029409-48e6eb19e1c3?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-beaver',
    name: 'Baby Beaver - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated beaver fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Hardworking cutie!',
    image: 'https://images.unsplash.com/photo-1633621827350-4e30e9bbb9fa?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-cat',
    name: 'Baby Cat - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated cat fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Purr-fect companion!',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-crocodile',
    name: 'Baby Crocodile - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated crocodile fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Snappy fun!',
    image: 'https://images.unsplash.com/photo-1550699026-4114bbf4fb49?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-arctic-fox',
    name: 'Baby Arctic Fox - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated arctic fox fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Snowy cuteness!',
    image: 'https://images.unsplash.com/photo-1552825973-5a6f1e7a3d6e?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-fox',
    name: 'Baby Fox - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated fox fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Woodland wonder!',
    image: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-goldfish',
    name: 'Baby Goldfish - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated goldfish fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Golden swimmer!',
    image: 'https://images.unsplash.com/photo-1520990269687-b48f8df42d7f?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-mouse',
    name: 'Baby Mouse - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated mouse fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Tiny and adorable!',
    image: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-otter',
    name: 'Baby Otter - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated otter fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Playful river friend!',
    image: 'https://images.unsplash.com/photo-1545671913-b89ac1b4ac10?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-pig',
    name: 'Baby Pig - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated pig fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Oink-tastic!',
    image: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-platypus',
    name: 'Baby Platypus - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated platypus fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Unique creature!',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-polar-bear',
    name: 'Baby Polar Bear - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated polar bear fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Arctic cuddler!',
    image: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-rhino',
    name: 'Baby Rhino - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated rhino fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Mighty mini!',
    image: 'https://images.unsplash.com/photo-1551927336-575d8e829c8a?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },
  {
    id: 'baby-sea-turtle',
    name: 'Baby Sea Turtle - Articulated Fidget',
    price: 1.00,
    description: '3D printed articulated sea turtle fidget toy. Baby size (0.75"). Made from eco-friendly biodegradable PLA. Ocean baby!',
    image: 'https://images.unsplash.com/photo-1591025207163-942350e47db2?w=500&q=80',
    category: 'Fidget Toys - Baby',
    stock: 50,
  },

  // Additional Big Animals
  {
    id: 'big-axolotl',
    name: 'Big Axolotl - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated axolotl fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Detailed amphibian!',
    image: 'https://images.unsplash.com/photo-1617510029409-48e6eb19e1c3?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-beaver',
    name: 'Big Beaver - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated beaver fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Builder buddy!',
    image: 'https://images.unsplash.com/photo-1633621827350-4e30e9bbb9fa?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-cat',
    name: 'Big Cat - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated cat fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Feline favorite!',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-crocodile',
    name: 'Big Crocodile - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated crocodile fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Detailed predator!',
    image: 'https://images.unsplash.com/photo-1550699026-4114bbf4fb49?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-arctic-fox',
    name: 'Big Arctic Fox - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated arctic fox fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Winter beauty!',
    image: 'https://images.unsplash.com/photo-1552825973-5a6f1e7a3d6e?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-dolphin',
    name: 'Big Dolphin - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated dolphin fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Ocean intelligence!',
    image: 'https://images.unsplash.com/photo-1607153333879-c174d265f1d2?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-goldfish',
    name: 'Big Goldfish - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated goldfish fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Lucky swimmer!',
    image: 'https://images.unsplash.com/photo-1520990269687-b48f8df42d7f?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-mouse',
    name: 'Big Mouse - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated mouse fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Charming critter!',
    image: 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-narwhal',
    name: 'Big Narwhal - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated narwhal fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Unicorn of the sea!',
    image: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-otter',
    name: 'Big Otter - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated otter fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Playful swimmer!',
    image: 'https://images.unsplash.com/photo-1545671913-b89ac1b4ac10?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-panda',
    name: 'Big Panda - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated panda fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Bamboo lover!',
    image: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-pig',
    name: 'Big Pig - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated pig fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Farm favorite!',
    image: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-platypus',
    name: 'Big Platypus - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated platypus fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Quirky wonder!',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-polar-bear',
    name: 'Big Polar Bear - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated polar bear fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Arctic king!',
    image: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
  {
    id: 'big-rhino',
    name: 'Big Rhino - Articulated Fidget',
    price: 5.00,
    description: '3D printed articulated rhino fidget toy. Big size (1.5"). Made from eco-friendly biodegradable PLA. Powerful beast!',
    image: 'https://images.unsplash.com/photo-1551927336-575d8e829c8a?w=500&q=80',
    category: 'Fidget Toys - Big',
    stock: 30,
  },
];
